### ISSUE TITLE
🚀 - handle links for copied text

### ISSUE THREAD

**Issue by Ultraviolence322** [taiga-family/editor#1063]
### Description

1. Copy text with link from https://taiga-family.github.io/tui-editor/starter-kit

![image](https://github.com/taiga-family/tui-editor/assets/53703949/cab118aa-4514-47f2-bb08-2b3fd36ed53c)
2. Paste it in Outlook
Text pasted with link 

![image](https://github.com/taiga-family/tui-editor/assets/53703949/0cc7588d-b07a-4288-801e-ff11c21003cc)

But if paste this text in Telegram there will be no link
Is it possible to handle links for apps like Telegram?

By the way if copy text with link from Outlook and paste in Telegram there will be link (macOS)

**Comment by splincode** [comment]
Hello, I can't reproduce on my Outlook version


![Image](https://github.com/user-attachments/assets/2fbe77a7-a161-493e-9c80-cf230d8dc053)

![Image](https://github.com/user-attachments/assets/1eee2d8f-5d4e-46e0-b102-450a26f9d876)
