### ISSUE TITLE
🚀 - `@tiptap/extension-*` dependencies should be marked as optional

### ISSUE THREAD

**Issue by hakimio** [taiga-family/editor#1098]
### Description

Reopening #1092 since PR #1093 was reverted.

**Comment by splincode** [comment]
I'm not sure if I should do this after the build crashed

**Comment by hakimio** [comment]
The build failed because **optional peer** dependencies were not installed. You are relying on npm automatically installing peer dependencies, which other package managers like `yarn` don't do.

I don't see why it should be mandatory to install all the extensions even you are only using some of them.

@waterplea what's your opinion about this?

**Comment by waterplea** [comment]
> The build failed because **optional peer** dependencies were not installed. You are relying on npm automatically installing peer dependencies, which other package managers like `yarn` don't do.
> 
> I don't see why it should be mandatory to install all the extensions even you are only using some of them.
> 
> @waterplea what's your opinion about this?

Sounds like we need all those deps explicitly stated in our demo app/CI, but keep them optional in our library published package.json, right?

**Comment by splincode** [comment]
`need all those deps explicitly`

users will have to specify a lot of packages themselves

**Comment by hakimio** [comment]
> Sounds like we need all those deps explicitly stated in our demo app/CI, but keep them optional in our library published package.json, right?

Yes, that's the idea.

**Comment by hakimio** [comment]
> users will have to specify a lot of packages themselves

By default, npm installs non-optional `peer dependencies` automatically, but because you [enabled `legacy-peer-deps`](https://github.com/taiga-family/editor/blob/fdd39a41526c053faef2b50c053f079357417b91/.npmrc#L5), they were not installed. The user will have to install manually some of the extensions, but in many cases just installing the [StarterKit](https://tiptap.dev/docs/editor/api/extensions/starter-kit) should be enough.
Still it might be a good idea to update the docs with information about the optional peer dependencies, what users need to install and how to configure extensions.

**Comment by splincode** [comment]
Do not use `legacy-peer-deps`

**Comment by hakimio** [comment]
I am not. Your `v1` branch is.

**Comment by splincode** [comment]
**v1.x** -> we use [dependencies](https://github.com/taiga-family/editor/blob/v1.x/projects/tui-editor/package.json#L16) for legacy-peer-deps

**main** -> we use [peerDependencies](https://github.com/taiga-family/editor/blob/main/projects/editor/package.json#L16) for user who don't use legacy-peer-deps

**Comment by waterplea** [comment]
I think technically it's a good idea to not force people to install dependencies they might not need. Sure, most of our internal users will use full default kit, but if we are trying to develop a widely used modern solution, we should probably embrace this approach. We can add those packages with migration script for our current users and add it to the docs to reflect what you need to add if you want to use full toolset.

**Comment by hakimio** [comment]
Sounds good to me.

**Comment by splincode** [comment]
@waterplea sure

**Comment by splincode** [comment]
Fixed by v2.x

**Comment by hakimio** [comment]
@splincode `@maskito/angular` should be optional too. 
Also, it might be a good idea to add a note to the docs.

**Comment by waterplea** [comment]
I don't think we need Maskito at all in the editor?

**Comment by splincode** [comment]
`color-input` use it
