### ISSUE TITLE
🐞 - Links are not changed in Safari

### ISSUE THREAD

**Issue by dkuptsova** [taiga-family/editor#1100]
### Playground Link

https://taiga-ui.tcsbank.ru/components/editor

### Case 1
1. Paste link into Editor
2. Click on the link
3. Click "Edit"
4. Change the link
5. Click "Save"

**Result:** the link has not been changed

### Case 2
1. Paste the long link into Editor
2. Click on the link
3. Click "Edit"
4. Place the cursor in the field and move it to the end

**Result:** the end has not been reached
Additional: If after case 2 try to change the link new characters will be placed in the wrong place

Safari version: 17.3.1 (19617.2.4.11.12)
https://github.com/taiga-family/editor/assets/152492774/85bdacc1-80e7-47be-a888-72dd908e04e6

### Angular version

17.3.9

### Taiga UI version

3.38.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Fixed by v1.38
