### ISSUE TITLE
🐞 - Color Picker return color only RGBA format

### ISSUE THREAD

**Issue by Givaka** [taiga-family/editor#1262]
### Description

The problem is that tui-color-selector only passes RGBA color to tui-input-color . Despite the fact that HEX mode is selected

### Angular version

18.0.1

### Taiga UI version

3.81.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by p-ivannikov** [comment]
i will take it

**Comment by waterplea** [comment]
Frankly, I'm not sure this is a bug. It's better to have control value in stable format and just use parsing functions to turn it into anything you want, maybe?

**Comment by splincode** [comment]
`maybe?` sure
