### ISSUE TITLE
🐞 -  Bug - TuiNodeViewNg- Node Conflict after dragging and dropping 

### ISSUE THREAD

**Issue by KhaledGabr** [taiga-family/editor#1281]
### Description

https://github.com/user-attachments/assets/c4ea1bd7-1b70-4bc7-93d7-dad42021e953

The node displays the content of the first component, instead of the second after dragging it from one place to the other.
This doesn't only happen with TuiImageEditor but with any component really, so it has to do with how  TuiNodeViewNg deals with nodes.

### Angular version

latest - deployed

### Taiga UI version

v2.5.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Could you add stackblitz or how can I reproduce it?

**Comment by splincode** [comment]
I can't reproduce on MacOS

@hakimio do you have that problem?

**Comment by hakimio** [comment]
Yes, I can reproduce.
Chrome 129 on Windows 10.
Gif:
![image-bug](https://github.com/user-attachments/assets/c0c6258a-9b8a-46ef-a1cd-cd1b6f56992d)

No warnings in console.

**Comment by splincode** [comment]
Can you help me with that bug? I can't reproduce on MacOS and I don't have Windows machine

**Comment by hakimio** [comment]
Any pointers how to debug this?

**Comment by splincode** [comment]
I don't have any ideas

**Comment by hakimio** [comment]
@KhaledGabr can you verify that it's not `@tiptap` upstream issue?

**Comment by hakimio** [comment]
@KhaledGabr there is nothing in `TuiComponentRenderer` or `TuiNodeView` which deals with node dragging.
The dragging functionality is handed over to tiptap and its extensions:
https://github.com/taiga-family/editor/blob/6c8c4fc4ed44ee2639dad989ed2835421715bbb6/projects/editor/extensions/tiptap-node-view/index.ts#L157

Can you show that the same image dragging works correctly in [`tiptap` vanilla](https://tiptap.dev/docs/examples/basics/images)?


BTW, `TuiComponentRenderer` and `TuiNodeView` should be exactly the same like in `ngx-tiptap` since according to the comment the code was copied from `ngx-tiptap`:
https://github.com/taiga-family/editor/blob/6c8c4fc4ed44ee2639dad989ed2835421715bbb6/projects/editor/extensions/tiptap-node-view/index.ts#L16

**Comment by hakimio** [comment]
Ok, sorry. The issue might be here:
https://github.com/taiga-family/editor/blob/6c8c4fc4ed44ee2639dad989ed2835421715bbb6/projects/editor/extensions/image-editor/image-editor.extension.ts#L25

I'll look into it.

**Comment by hakimio** [comment]
Yes, you are right. The `pasteImage()` doesn't have anything to do with this. During drag operation `dataTransfer.files` array is empty and `pasteImage()` doesn't load any images.

I have also debugged `TuiComponentRenderer`, `TuiNodeView` and the image editor extensions. Could not find anything that could be replacing the image.

Wrong image comes in the `props` argument in the following line. This seems to be called from `tiptap`.
https://github.com/taiga-family/editor/blob/6c8c4fc4ed44ee2639dad989ed2835421715bbb6/projects/editor/extensions/image-editor/image-editor.extension.ts#L118

So, I still don't have any ideas what in the `tui-editor` could be causing this behavior and I still believe it's coming from `tiptap` side. Feel free to prove me wrong.

**Comment by hakimio** [comment]
Ok, found only a [not so great] workaround for the issue. If you remove `@tuiPure` from the following line, the image will first get the wrong image source and then will be updated with the correct one (there is still a flash of the wrong image):
https://github.com/taiga-family/editor/blob/6c8c4fc4ed44ee2639dad989ed2835421715bbb6/projects/editor/extensions/image-editor/image-editor.component.ts#L103
