### ISSUE TITLE
🐞 - clicking image edit button submits the form

### ISSUE THREAD

**Issue by justhugebrat** [taiga-family/editor#1286]
### Description

1. Add image
2. Click edit button
![Снимок экрана 2024-08-26 в 13 55 05](https://github.com/user-attachments/assets/caa75373-7886-4c9e-bd76-e388ae97898e)

### Angular version

14

### Taiga UI version

1.59.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Fixed by new version
