### ISSUE TITLE
🐞 - images are not loading

### ISSUE THREAD

**Issue by justhugebrat** [taiga-family/editor#1306]
### Description

- click image button
- choose and add image

https://github.com/user-attachments/assets/1a514cdd-e356-4856-be48-14fb1c36432f

### Angular version

14

### Taiga UI version

3.87.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Don't use VPN

**Comment by justhugebrat** [comment]
Didn't help

**Comment by splincode** [comment]
Show me your devtools console

**Comment by splincode** [comment]
Sorry, I have a problem too, thank you for issue
