### ISSUE TITLE
🐞 - invalid input border color is not applied to the editor

### ISSUE THREAD

**Issue by hakimio** [taiga-family/editor#1327]
### Description

When editor's form control is invalid, red input's outline is not applied to the editor.

### Angular version

18

### Taiga UI version

4

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
This is not fixed.

**Comment by waterplea** [comment]
Hmm, it is fixed in main, but we need to properly implement `Appearance` anyway, I'll fix it.
