### ISSUE TITLE
🐞 - `@tiptap/extension-*` peer dependencies should be marked as optional

### ISSUE THREAD

**Issue by hakimio** [taiga-family/editor#1329]
### Description

Reopening #1092/#1098 since now none of the `tiptap extensions` are marked as optional.
It's extremely annoying to be forced to install all those extensions you don't want to use.
And no, I am not using `npm`. I am using `yarn`.
@waterplea

![image](https://github.com/user-attachments/assets/fae8cb54-3eae-49c6-8bbc-6c5f94612300)

### Angular version

18

### Taiga UI version

4

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
@hakimio which yarn version do you use?

**Comment by hakimio** [comment]
`4.4.0`

**Comment by waterplea** [comment]
Unfortunately it seems like there's no easy way to just call `npm install --include-optional` or something similar, unless I'm missing something. Which means not enforcing `yarn` users to manually add this list requires all `npm` users who don't care and just want to use editor with all the features to manually add a ton of packages. This seems like a bad tradeoff to me. Apparently yarn believes it should be handled with a plugin, pretty sure there should be something like that already available:
https://github.com/yarnpkg/yarn/issues/1503#issuecomment-753624157

**Comment by hakimio** [comment]
How many editor users need **all** the plugins? editor defaults could be changed to include just the essential/main plugins most users need and make the rest optional. Who needs markdown, youtube, table, etc? Users who need that, can add those by following a guide.

**Comment by splincode** [comment]
Our proprietary projects use many plugins by default

**Comment by splincode** [comment]
Use `npm` instead of `yarn` and everything will be fine

**Comment by splincode** [comment]
I have an idea for that issue

**Comment by hakimio** [comment]
@splincode the "fix" doesn't do anything other than introduce additional dependency on `@taiga-ui/editor-extensions`. Now basically you have non-optional peer dependency on `@taiga-ui/editor-extensions` and the `@taiga-ui/editor-extensions` has non-optional peer dependencies on all tiptap extensions.

Now, that you also restricted extension versions to patch versions and lost any peer dependency advantage, might as well just replace peer dependencies with hard dependencies. At least in that case `yarn` users won't have to add them to their dependencies.

On slightly related news, tree-shaking doesn't seem to work with the editor. All the dependencies to `markdown`, `posemirror-table`, etc are still included in the bundle even I have customized editor's extensions:

![image](https://github.com/user-attachments/assets/7195b4f6-d654-4221-b8e1-22a363847481)

```ts
import type {Extension, Mark, Node} from '@tiptap/core';
import {TuiStarterKit, TuiTabExtension, TuiLink} from '@taiga-ui/editor';

export const TUI_EDITOR_DEFAULT_EXTENSIONS: ReadonlyArray<
    Extension | Mark | Node | Promise<Extension | Mark | Node>
> = [
    TuiStarterKit.configure({
        heading: false,
        code: false,
        codeBlock: false,
        dropcursor: false,
        gapcursor: false
    }),
    import('@tiptap/extension-text-style').then(({default: textStyle}) => textStyle),
    import('@tiptap/extension-underline').then(({default: underline}) => underline),
    TuiLink,
    TuiTabExtension
];
```

**Comment by splincode** [comment]
i wash my hands of this job

**Comment by waterplea** [comment]
Well, at least tree shaking should definitely work. @hakimio, could you file a separate issue please? Preferably with a repo so we can be sure about bundler, angular version etc.

**Comment by hakimio** [comment]
In case any other yarn user faces this issue, as a temporary workaround peer dependency warnings can be suppressed with `logFilters` option in `.yarnrc.yml` config:
```
logFilters: [{
  code: 'YN0002',
  level: 'discard'
}, {
  code: 'YN0086',
  level: 'discard'
}]
```
[Config description](https://yarnpkg.com/configuration/yarnrc#logFilters)
