### ISSUE TITLE
🐞 - Doesn't work feature "Resizable image"

### ISSUE THREAD

**Issue by IlyaSavchenko** [taiga-family/editor#1384]
### Playground Link

[_Link_](https://stackblitz.com/edit/stackblitz-starters-mvfrcz?file=src%2Fmain.ts)

### Description

After added image I can't change it sizes when drag borders of image

https://github.com/user-attachments/assets/15b80aa4-b61c-49dc-9b47-d7c82f4a7dc8

Editor version: 
![image](https://github.com/user-attachments/assets/1ebca5e5-02d9-4ca8-9463-cf2ed371c46c)

### Angular version

17.3.12

### Taiga UI version

4.5.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
forgot `NG_EVENTS_PLUGIN`
