### ISSUE TITLE
🚀 - Rename `exampleText` to `placeholder`

### ISSUE THREAD

**Issue by hakimio** [taiga-family/editor#1463]
### Description

Is it intentional that the placeholder doesn't disappear when editor contains text like it does in [tiptap demo](https://tiptap.dev/docs/editor/extensions/functionality/placeholder)?

### Taiga UI version

4.8.1

### Browser Used

Chrome

### OS Used

Windows

**Comment by splincode** [comment]
@hakimio could you add video what about you?

**Comment by hakimio** [comment]
Is there any need for a video? I expect the editor's label like `Start typing` in the demo to disappear when you actually start typing. Doesn't seem to be the case now.

![start typing](https://github.com/user-attachments/assets/9bd0669c-50b7-4dc2-99ec-b19dbc540584)

**Comment by splincode** [comment]
@waterplea it was always here by design. Do we need change it?

**Comment by hakimio** [comment]
If the static label is intentional maybe temporary placeholder could be provided some other way?

**Comment by hakimio** [comment]
It's a little confusing when the CSS class applied to the label's container says `t-editor-placeholder` 🙂

**Comment by splincode** [comment]
maybe it can be rename to `t-label`

**Comment by splincode** [comment]
<img width="747" alt="image" src="https://github.com/user-attachments/assets/ce3620ec-5c6c-44b8-b57d-089b692f62ff">

https://taiga-family.github.io/editor/starter-kit?exampleText=Placeholder

<img width="486" alt="image" src="https://github.com/user-attachments/assets/05052fb7-8ebd-48af-9537-e811b064576c">

**Comment by waterplea** [comment]
Yeah, we renamed those classes in v4 for the rest of Taiga UI :) And exampleText got dropped in new textfields in favor of native palceholder. So it appears that we should just close this issue and put a TODO to rename exampleText into placeholder in next major?

**Comment by hakimio** [comment]
Maybe `exampleText` could also be renamed to `placeholder`?

**Comment by splincode** [comment]
Let's not close this issue so as not to forget

**Comment by waterplea** [comment]
> Let's not close this issue so as not to forget

We can just add `placeholder` and use `placeholder || exampleText` and deprecate `exampleText`

**Comment by hakimio** [comment]
The placeholder tiptap extension added in [starter kit](https://github.com/taiga-family/editor/blob/6c8c4fc4ed44ee2639dad989ed2835421715bbb6/projects/editor/extensions/starter-kit/index.ts#L193) seems to be useless since `exampleText` doesn't require it and I don't see where else it could be used.
