### ISSUE TITLE
🐞 - Hard break requires to press `Enter` twice

### ISSUE THREAD

**Issue by hakimio** [taiga-family/editor#1464]
### Description

Hard break (`<br>`) can be inserted by pressing `Shift + Enter`.
If you position the text cursor at the end of a paragraph or some other tag, then to insert the hard break you have to press `Shift + Enter` twice.
If you put the cursor inside a paragraph, then it works correctly.
This does not seem to be the case in [tiptap demo](https://tiptap.dev/docs/examples/basics/default-text-editor) where it always only requires a single press.

### Taiga UI version

4.8.1

### Browser Used

Chrome

### OS Used

Windows

**Comment by hakimio** [comment]
The bug seems to be the result of the following CSS:

![trailing break](https://github.com/user-attachments/assets/d42f7eba-e339-483b-923f-156e0e16256b)

https://github.com/taiga-family/editor/blob/6c8c4fc4ed44ee2639dad989ed2835421715bbb6/projects/editor/components/editor-socket/editor-socket.component.less#L38

**Comment by splincode** [comment]
Could you fix it?

**Comment by hakimio** [comment]
While I can remove the offending CSS, I have no idea why it was added there in the first place. Maybe it serves some purpose?

**Comment by splincode** [comment]
For compat with https://taiga-family.github.io/editor/groups maybe

<img width="640" alt="image" src="https://github.com/user-attachments/assets/062dc8b8-2b08-4562-95a3-7580c4fb031f">

**Comment by hakimio** [comment]
Ok, then you'll have to look into this since I don't know how the group extension supposed to work.

**Comment by hakimio** [comment]
@splincode the workaround was added as a fix for some gapcursor style issues:
https://github.com/taiga-family/editor/commit/fe0ce2210d4ad4fba252a11ff4522cd9e5d4c7e8

Should I just remove the offending CSS or do you plan to come up with some better solution for this?

**Comment by splincode** [comment]
`Should I just remove the offending CSS or do you plan to come up with some better solution for this?`

drop it
