### ISSUE TITLE
🐞 - task list can not be indented using `tab` keyboard shortcut

### ISSUE THREAD

**Issue by hakimio** [taiga-family/editor#1465]
### Code Example URL

n/a

### Description

Unlike ordered and unordered lists, task list can not be indented using `tab` keyboard shortcut.

### Taiga UI version

4.8.1

### Browser Used

Chrome

### OS Used

Windows

**Comment by hakimio** [comment]
This actually works as long as `TuiTabExtension` is imported before the task list extension.

**Comment by hakimio** [comment]
@splincode just a thought: to avoid this kind of issues in the future maybe `indent` extension's [priority](https://tiptap.dev/docs/editor/extensions/custom-extensions/extend-existing#priority) could be increased?

**Comment by splincode** [comment]
@hakimio sure, you can make PR please
