### ISSUE TITLE
🐞 - TuiEditor: the value in the component is incorrectly updated when it is passed as an empty string using `formControl`

### ISSUE THREAD

**Issue by algashev123** [taiga-family/editor#1522]
### Reproduction url

https://taiga-family.github.io/editor/starter-kit?ngModel=&placeholder=Test

### Description

An empty string is incorrectly processed by the TuiEditor component. Playback Steps:
1. Open the showcase at the specified link;
2. In the `ngModel: Example pass HTML code` input, delete the value through the cross;
3. Enter something into the Editor component;
4. Repeat step 2;
5. Look at the result.

Expected behavior:
The component has cleared, there is no value in it and the placeholder is visible.

Current result:
The text in the input is not cleared, the placeholder is layered on the text
<img width="1554" alt="Снимок экрана 2024-10-09 в 17 06 48" src="https://github.com/user-attachments/assets/79ae0246-d3f7-432c-a4ea-69a7a49d4f63">

### Taiga UI version

4.15.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by splincode** [comment]
I'll take this issue on Monday
