### ISSUE TITLE
🐞 - hotkeys of disabled tools keep on working

### ISSUE THREAD

**Issue by Gleb1nho** [taiga-family/editor#1523]
### Reproduction url

https://stackblitz.com/edit/angular-yiw4rr?file=src%2Fapp%2Fapp.component.ts

### Description

Hotkeys of disabled tools keep on working.

Steps to reproduce:
1. Create editor
2. Add only undo/redo tool (or no tools at all)
3. Type some text into the editor
4. Select the text
5. Press `cmd + b`/`ctrl + b`

Result: text gets bolder
Expected result: text does not change

Also works with other hotkeys: `cmd + u`, `cmd + opt + 1/2/3`, etc.

### Taiga UI version

4.9.0

### Browser Used

Chrome

### OS Used

macOS

**Comment by hakimio** [comment]
If you don't want some extensions, you can just provide your own set of editor extensions instead of the default ones:
https://github.com/taiga-family/editor/blob/fcf629b839d1d6b682cbfef12863c61c6a4a2a0a/projects/demo/src/app/pages/font/examples/2/index.ts#L26

**Comment by waterplea** [comment]
I think this issue is about adding this info to the docs, as people might think when you do not have a button in toolbar — hotkeys would also stop working, but these are actually two separate things.
