### ISSUE TITLE
🐞 - `attrs` property of `TuiEditorAttachedFile` is ignored when setting file link

### ISSUE THREAD

**Issue by hakimio** [taiga-family/editor#1624]
### Reproduction url

https://taiga-family.github.io/editor/upload-files

### Description

`attrs` property is ignored when calling `tuiEditor?.editor?.setFileLink()`:
```ts
tuiEditor?.editor?.setFileLink({
    name: 'my-file.png',
    link: '#',
    attrs: {
        'data-id': '123',
        'data-filename': 'my-file.png'
    }
});
```

The attributes are never set on the link.
https://github.com/taiga-family/editor/blob/f73c397c277c2ad37dd5e87f7244dc2bc67b55fd/projects/editor/extensions/file-link/index.ts#L35

### Taiga UI version

4.19.0

### Browser Used

Chrome

### OS Used

Windows

**Comment by splincode** [comment]
Can you help with it?

**Comment by hakimio** [comment]
Ok, I'll create a PR.
