### ISSUE TITLE
🚀 - Mention extension usage example

### ISSUE THREAD

**Issue by hakimio** [taiga-family/editor#815]
### Description

Would be nice to have an example of `@tiptap/extension-mention` extension usage example with `tui-editor` and `tuiDropdown`.
There is [an example](https://stackblitz.com/edit/ngx-tiptap-mentions?file=src%2Fapp%2Fapp.component.ts) for `ngx-tiptap` but because of the way `tuiDropdown` directive works, creating sth similar with "Taiga UI" components seems a bit more tricky.
@waterplea

**Comment by hakimio** [comment]
@splincode 
- it doesn't seem to be possible to select suggestion result using up/down arrows.
- autocompletion list should appear after just entering `@` instead of waiting for user to enter `@a`.
- how do you assign custom CSS classes to the mention `span` tag?

**Comment by splincode** [comment]
`how do you assign custom CSS classes to the mention span tag?` what do you mean?

**Comment by hakimio** [comment]
I want to have:
`<span class="my-mention" data-type="mention">@a.inkin</span>`

**Comment by splincode** [comment]
okey

**Comment by hakimio** [comment]
@splincode it is still not possible to select autocompletion results by using up/down arrow keys like when using `@tiptap/extension-mention` extension.
See the following "Taiga UI" example: https://taiga-ui.dev/directives/dropdown-selection#textarea

**Comment by splincode** [comment]
`it is still not possible to select autocompletion results by using up/down arrow keys like when using` yes, I don't know how fix it

**Comment by hakimio** [comment]
Well, if I can achieve this using the original `@tiptap/extension-mention`, it should be possible with your custom extension.
Not being able to select an option with arrow keys is a major accessibility issue.

```
mentions-list.component.ts
```
![image](https://github.com/taiga-family/tui-editor/assets/768105/36d31aec-e801-4a18-8b0e-fd75feed87c4)

```
create-mentions-options.ts
```
![image](https://github.com/taiga-family/tui-editor/assets/768105/d7813797-5809-4b0b-ad14-ab0287e9331c)

**Comment by waterplea** [comment]
Reopening since we need that keyboard support. However we're kind of short on time these days, trying to push Taiga UI 4.0 so this might take a while.

**Comment by splincode** [comment]
@waterplea https://taiga-family.github.io/tui-editor/mention
I fixed it, you can try paste `@` and use keyboard

**Comment by hakimio** [comment]
@splincode but now it's impossible to filter the list?

**Comment by waterplea** [comment]
Also we need `Esc` to close the dropdown.

**Comment by hakimio** [comment]
Also, there is a bug with dropdown placement:
![image](https://github.com/taiga-family/tui-editor/assets/768105/c341175b-c100-458d-8f79-9e972bd8d534)

To reproduce:
- Put the cursor on the third line
- Press "Ctrl + A" and "Delete"
- Type "@"

**Comment by splincode** [comment]
`but now it's impossible to filter the list?`

why? you can

https://github.com/taiga-family/tui-editor/assets/12021443/03c1514c-c0c7-49eb-8f54-570f24f1290d

**Comment by waterplea** [comment]
> `but now it's impossible to filter the list?`
> 
> why? you can
> 
>  Screen.Recording.2024-04-12.at.16.06.43.mov

Whenever I press @ focus shifts to the dropdown and remains there, I'm unable to type

**Comment by waterplea** [comment]
> After pressing `@` it automatically focuses the dropdown. Typing anything after that to filter dropdown is impossible. It should only focus the dropdown when I press up or down arrow. Before that I should be able to filter the menu.

Our dropdowns in Taiga UI move focus back to the input when you start typing, maybe something like this can be added here as well.

**Comment by splincode** [comment]
`Our dropdowns in Taiga UI move focus back to the input when you start typing, maybe something like this can be added here as well.` I don't know, it doesn't work with `[contenteditable]`

**Comment by waterplea** [comment]
This method takes care of it:
https://github.com/taiga-family/taiga-ui/blob/v3.x/projects/core/components/hosted-dropdown/hosted-dropdown.component.ts#L222
