### ISSUE TITLE
🐞 - Editor reloads images on every render

### ISSUE THREAD

**Issue by YuliaTsareva** [taiga-family/editor#945]
### Description

How to reproduce:
1. Open dev tools.
2. Add image to editor.
3. Trigger re-render (click on page, scroll it, switch tabs).

There are multiple image requests in Network.

### Angular version

15.2.1

### Taiga UI version

3.69.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
@YuliaTsareva I can't reproduce


https://github.com/taiga-family/tui-editor/assets/12021443/8daedd8a-5834-4c66-8d04-963671d469b6

**Comment by splincode** [comment]
`uses base64, of course it will no network requests.` not a problem for other case

https://github.com/taiga-family/tui-editor/assets/12021443/94d0efe0-283c-4dca-9870-37f2c9b7f46b

**Comment by Ultraviolence322** [comment]
@splincode but in network many requests 
https://github.com/taiga-family/tui-editor/assets/53703949/8fe25826-ddbf-4904-917f-718de2cc7ebc
